### ISSUE TITLE
Failed to import games from ATLauncher. Cannot recognize the string as valid DateTime value.

### ISSUE THREAD

**Issue by Zergiv2** [ASchoe311/ATLauncher-Integration#1]
![image](https://github.com/user-attachments/assets/7ce90c0f-4167-4614-9631-b99eb70a05e2)

Failed to import games from
ATLauncher.
Cannot recognize the
string as valid DateTime
value.

the installation path is ok, but I get this error

**Comment by ASchoe311** [comment]
Can you post the relevant information from playnite.log please?

**Comment by Zergiv2** [comment]
![image](https://github.com/user-attachments/assets/7d1b85f6-cde4-4a55-95d0-6bfcc619d341)

**Comment by ASchoe311** [comment]
Just pushed out a new release, give it a try and let me know if it works [Release 1.1.2](https://github.com/ASchoe311/ATLauncher-Integration/releases/tag/v1.1.2)

**Comment by ASchoe311** [comment]
> ![image](https://private-user-images.githubusercontent.com/82688396/367075815-7d1b85f6-cde4-4a55-95d0-6bfcc619d341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTAzMjUsIm5iZiI6MTcyNjE5MDAyNSwicGF0aCI6Ii84MjY4ODM5Ni8zNjcwNzU4MTUtN2QxYjg1ZjYtY2RlNC00YTU1LTk1ZDAtNmJmY2M2MTlkMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAxMTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZWFjN2UzOTAyZTM2YmZjNDU5ZDU3YmQwMTIzOWRiMTg5OGY5NTJkOGQ1ZDJmOGJkNjA0YTg0NzJlNjE1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A7AHgsoUHgXko0XJI2qJ5cFuIFkb7Kdf1E3l13b6J7s)

Also, would you be able to post the instance.json file that the plugin failed on? You can check extensions.log to see which instance the plugin was attempting to import

**Comment by Zergiv2** [comment]
after installing the update, it works, thanks
